# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Build using Maven

on:
  push:
    paths:
      - 'java/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./java   

jobs:
  build:
    runs-on: ubuntu-latest
    env:

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v2
      - name: ⚙️ Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: 💽 Restore Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: 🧪 Run Build
        run: mvn clean verify
